-- Tạo Database (nếu chưa có)
CREATE DATABASE WasteManagementSystem;
GO
USE WasteManagementSystem;
GO

-- 1. Bảng Người dùng
CREATE TABLE USER_ACCOUNT (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    fullName NVARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    passwordHash NVARCHAR(MAX) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('CITIZEN', 'COLLECTOR', 'OPERATOR', 'ADMIN')),
    isActive BIT DEFAULT 1,
    createdAt DATETIME DEFAULT GETDATE()
);

-- 2. Kho điểm của Công dân
CREATE TABLE CITIZEN_INVENTORY (
    citizenId UNIQUEIDENTIFIER PRIMARY KEY FOREIGN KEY REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE,
    totalPoint INT DEFAULT 0,
    currentPoint INT DEFAULT 0
);

-- 3. Báo cáo rác thải
CREATE TABLE REPORT (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    citizenId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(id),
    operatorId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES USER_ACCOUNT(id), -- Người duyệt
    description NVARCHAR(MAX),
    imageUrl VARCHAR(MAX),
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ASSIGNED', 'COLLECTED', 'REJECTED')),
    createdAt DATETIME DEFAULT GETDATE()
);

-- 4. Chi tiết loại rác trong báo cáo
CREATE TABLE REPORT_WASTE (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    reportId UNIQUEIDENTIFIER UNIQUE NOT NULL FOREIGN KEY REFERENCES REPORT(id) ON DELETE CASCADE,
    wasteCategory VARCHAR(20) NOT NULL CHECK (wasteCategory IN ('ORGANIC', 'INORGANIC', 'RECYCLABLE', 'HAZARDOUS')),
    isAIRecommended BIT DEFAULT 0
);

-- 5. Phân công thu gom
CREATE TABLE COLLECTOR_ASSIGNMENT (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    reportId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES REPORT(id),
    collectorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(id),
    assignedBy UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES USER_ACCOUNT(id), -- Operator phân công
    assignedAt DATETIME DEFAULT GETDATE()
);

-- 6. Khu vực dịch vụ của người thu gom
CREATE TABLE SERVICE_AREA (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    collectorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(id),
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    radiusKm FLOAT NOT NULL
);

-- 7. Lịch sử giao dịch điểm
CREATE TABLE POINT_TRANSACTION (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    citizenId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(id),
    reportId UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES REPORT(id),
    actionType VARCHAR(20) NOT NULL CHECK (actionType IN ('EARN', 'SPEND')),
    reason VARCHAR(50) NOT NULL CHECK (reason IN ('REPORT_WASTE', 'VOUCHER_REDEEM')),
    point INT NOT NULL,
    createdAt DATETIME DEFAULT GETDATE()
);

-- 8. Danh mục Voucher
CREATE TABLE VOUCHER (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    name NVARCHAR(255) NOT NULL,
    discountPercent INT CHECK (discountPercent > 0 AND discountPercent <= 100),
    requiredPoint INT NOT NULL
);

-- 9. Voucher của người dùng
CREATE TABLE CITIZEN_VOUCHER (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    citizenId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES USER_ACCOUNT(id),
    voucherId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES VOUCHER(id),
    status VARCHAR(20) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'USED', 'EXPIRED')),
    acquiredAt DATETIME DEFAULT GETDATE()
);
GO